<a href="https://colab.research.google.com/github/ajgquional/LiL_PyTorch-Essential-Training-Deep-Learning/blob/main/Autograd_with_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Autograd with tensors

In [1]:
import torch

In [2]:
w = torch.randn(4, 3, requires_grad=True) # requires_grad=True so that PyTorch can keep track of the operations on the tensors and calculate the gradients

In [3]:
w

tensor([[-1.1231, -0.6223, -0.9334],
        [-0.8107, -0.6207, -0.9675],
        [-1.3901,  0.1450,  0.4756],
        [ 0.8533,  0.1602,  1.2434]], requires_grad=True)

Setting requires_grad to False then True again

In [4]:
w.requires_grad_(False)
w

tensor([[-1.1231, -0.6223, -0.9334],
        [-0.8107, -0.6207, -0.9675],
        [-1.3901,  0.1450,  0.4756],
        [ 0.8533,  0.1602,  1.2434]])

In [5]:
w.requires_grad_(True)

tensor([[-1.1231, -0.6223, -0.9334],
        [-0.8107, -0.6207, -0.9675],
        [-1.3901,  0.1450,  0.4756],
        [ 0.8533,  0.1602,  1.2434]], requires_grad=True)

New tensor

In [6]:
y = torch.exp(w)
print(y)

tensor([[0.3253, 0.5367, 0.3932],
        [0.4446, 0.5376, 0.3800],
        [0.2491, 1.1560, 1.6089],
        [2.3475, 1.1737, 3.4673]], grad_fn=<ExpBackward0>)


To verify that PyTorch keeps track of the operations

In [7]:
print(y.grad_fn)

In [8]:
outp = y.mean()
print(outp)

tensor(1.0517, grad_fn=<MeanBackward0>)


w.grad is still None yet since backward propagations is not being done yet

In [9]:
print(w.grad)

None


Now, backward propagation is done

In [10]:
outp.backward()

There are already gradients

In [11]:
print(w.grad)

tensor([[0.0271, 0.0447, 0.0328],
        [0.0370, 0.0448, 0.0317],
        [0.0208, 0.0963, 0.1341],
        [0.1956, 0.0978, 0.2889]])


If you don't want PyTorch to keep track of the operations and for the gradients to be calculated, detach the tensor from the computation history

In [12]:
print(w.detach())

tensor([[-1.1231, -0.6223, -0.9334],
        [-0.8107, -0.6207, -0.9675],
        [-1.3901,  0.1450,  0.4756],
        [ 0.8533,  0.1602,  1.2434]])


In [14]:
print(outp.requires_grad)
with torch.no_grad():
  outp = (w+y).mean()

print(outp.requires_grad)

True
False
