<a href="https://colab.research.google.com/github/ajgquional/LiL_PyTorch-Essential-Training-Deep-Learning/blob/main/Tensors_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors 

In [1]:
import torch

## zeros()
Creates a tensor (of a specified dimension) filled with zeros 

In [2]:
w = torch.zeros(4,3)
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape
Both shows the dimension of the tensor. Both size() and shape would return the same values - size() is special in PyTorch and shape is an alias to size() for those accustomed with NumPy

In [3]:
w.size()

torch.Size([4, 3])

In [4]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()
- randn() creates a tensor (of a specified dimension) of random numbers that are normally distributed (mean of 0, standard deviation of 1)
- randn_like() is similar to randn() but uses the size of other tensors

In [5]:
w = torch.rand(4, 3)
w

tensor([[0.8999, 0.6248, 0.6850],
        [0.7406, 0.7558, 0.7065],
        [0.0152, 0.3495, 0.1895],
        [0.0136, 0.4912, 0.2473]])

In [6]:
t = torch.randn_like(w)
t

tensor([[-0.8005, -0.8860, -1.6234],
        [-1.7480, -1.6165,  1.5297],
        [ 0.8042,  0.4114,  0.2686],
        [-0.4214, -0.7952,  0.3886]])

## fill_()
Mutates the tensor object and fills it up with a specified scalar value

In [7]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()
Reshapes a tensor

In [8]:
w

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
t = w.view(3, 4)
t

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
w.view(3, -1)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

## numpy()
- Converts a tensor to a NumPy array
- Important: If a Torch tensor is on the CPU, the Torch tensor and the NumPy array will share their underlying memory locations so changing one will change the other

In [10]:
w.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [11]:
type(w.numpy())

numpy.ndarray